trigger:
  branches:
    include:
      - '*'
    exclude:
      - 'main'

variables:
  - name: SBT_OPTS
    value: -Divy.home=$(Pipeline.Workspace)/.ivy2 -Dsbt.ivy.home=$(Pipeline.Workspace)/.ivy2


pool:
  vmImage: 'ubuntu-latest'

#todo create own scala runners
container: 'hseeberger/scala-sbt:graalvm-ce-21.3.0-java17_1.6.2_3.1.1'

steps:
  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      dockerVersion: 17.09.0-ce

  - task: Cache@2
    displayName: Docker Cache task
    inputs:
      key: 'docker|$(Agent.OS)|cache'
      path: $(Pipeline.Workspace)/docker
      cacheHitVar: DOCKER_CACHE_RESTORED

  - script: docker load -i $(Pipeline.Workspace)/docker/cache.tar
    displayName: Docker Cache restore
    condition: and(not(canceled()), eq(variables.DOCKER_CACHE_RESTORED, 'true'))

  - task: Cache@2
    displayName: sbt Cache task
    inputs:
      key: 'sbt | ivy2 | **/build.sbt | project/Dependencies.scala'
      restoreKeys: |
        sbt | ivy2 | **/build.sbt
        sbt | ivy2
      path: $(Pipeline.Workspace)/.ivy2

  - script: sbt compile
    displayName: Run compile

  - script: sbt test
    displayName: Run tests

  - script: docker images
    displayName: List docker images

  - script: sbt "dnwgGateway/runMain ManualBackfill"
    displayName: Run manual backfill
    continueOnError: true

  - script: sbt dnwgGateway/graalvm-native-image:stage
    displayName: 'Stage Binary'
    continueOnError: true

  - script: jar tvf $(Pipeline.Workspace)/dnwg-gateway/target/graalvm-native-image/stage/lib/nl.schiphol.dna.cdf.dnwg-gateway-0.1.0.jar
    displayName: 'List Binary'
    continueOnError: true

  - script: sbt dnwgGateway/graalvm-native-image:packageBin
    displayName: 'Create Binary'
    continueOnError: true

  - script: |
      mkdir -p $(Pipeline.Workspace)/docker
      docker save $(docker images "ghcr.io-graalvm-**" -q) -o $(Pipeline.Workspace)/docker/cache.tar
    displayName: Docker Cache save
    condition: and(not(canceled()), or(failed(), ne(variables.DOCKER_CACHE_RESTORED, 'true')))
    continueOnError: true

  - script: sbt dnwgGateway/docker:publishLocal
    displayName: 'Publish Docker Image'
    continueOnError: true
